postgresql:
  enabled: true
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: Never   # образ загружается offline на node1
  auth:
    username: platform
    password: platform
    database: platform
  persistence:
    size: 5Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi

redis:
  enabled: true
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: Never
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

platformApi:
  enabled: true
  image:
    repository: cloud-dwh/platform-api
    tag: "0.1.5"
    pullPolicy: Never
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
  env:
    # asyncpg DSN for SQLAlchemy
    DATABASE_URL: "postgresql+asyncpg://platform:platform@platform-postgresql:5432/platform"
    REDIS_URL: "redis://platform-redis:6379/0"
    KUBECONFIG_IN_CLUSTER: "true"
    HELM_CHARTS_PATH: "/charts/stacks"
    INGRESS_BASE_DOMAIN: "192.168.31.195.nip.io"
    SERVER_IP: "192.168.31.195"

platformUi:
  enabled: true
  image:
    repository: cloud-dwh/platform-ui
    tag: "0.1.5"
    pullPolicy: Never
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

ingress:
  enabled: true
  className: nginx
  host: platform.192.168.31.195.nip.io
  tls: true

server:
  ip: 192.168.31.195
  apiServer: https://192.168.31.195:6443
  baseDomain: 192.168.31.195.nip.io
